### ISSUE TITLE
How implement animation in UITableView or UICollectionView?

### ISSUE THREAD

**Issue by milanivarni** [daltoniam/DCAnimationKit#3]
Suppose I am using tableview in Xcode project.
I made on custom cell.
In that, I have 1 image view and 1 label, like following:

`- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{

CustomCell *cell = [tableView dequeueReusableCellWithIdentifier:@"Cell"];
    cell.lblName.text = arrIndexes[indexPath.row];
    NSInteger num = [[arrIndexes objectAtIndex:indexPath.row] integerValue];
    cell.imageView.image = [UIImage imageNamed:[NSString stringWithFormat:@"icon%ld.png",(long)num]];`

//Then I use DCAnimation like this
  **[cell.imageView bounceIntoView:cell direction:DCAnimationDirectionLeft];**

}`

## It is not working properly...

**Comment by daltoniam** [comment]
TableView and CollectionView's have recycling logic, so I don't think the code you have would work properly. Your best bet would probably be to use: 
```objc
- (void)tableView:(UITableView *)tableView 
  willDisplayCell:(UITableViewCell *)cell 
forRowAtIndexPath:(NSIndexPath *)indexPath
```

https://developer.apple.com/reference/uikit/uitableviewdelegate/1614883-tableview?language=objc

I can't guarantee that will work again due to the custom nature of a tableView, but probably your best bet. If that doesn't work than I would look at implementing a custom animator for a UICollectionView layout.
